/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppTicketsInternosRouteImport } from './routes/_app/tickets-internos'
import { Route as AppNovaOcorrenciaRouteImport } from './routes/_app/nova-ocorrencia'
import { Route as AppMeusTicketsRouteImport } from './routes/_app/meus-tickets'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppTicketIntRouteImport } from './routes/_app/ticket.$int'
import { Route as AppNpsRespostasRouteImport } from './routes/_app/nps/respostas'
import { Route as AppGestorKpisRouteImport } from './routes/_app/gestor/kpis'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTicketsInternosRoute = AppTicketsInternosRouteImport.update({
  id: '/tickets-internos',
  path: '/tickets-internos',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaOcorrenciaRoute = AppNovaOcorrenciaRouteImport.update({
  id: '/nova-ocorrencia',
  path: '/nova-ocorrencia',
  getParentRoute: () => AppRoute,
} as any)
const AppMeusTicketsRoute = AppMeusTicketsRouteImport.update({
  id: '/meus-tickets',
  path: '/meus-tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketIntRoute = AppTicketIntRouteImport.update({
  id: '/ticket/$int',
  path: '/ticket/$int',
  getParentRoute: () => AppRoute,
} as any)
const AppNpsRespostasRoute = AppNpsRespostasRouteImport.update({
  id: '/nps/respostas',
  path: '/nps/respostas',
  getParentRoute: () => AppRoute,
} as any)
const AppGestorKpisRoute = AppGestorKpisRouteImport.update({
  id: '/gestor/kpis',
  path: '/gestor/kpis',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/meus-tickets': typeof AppMeusTicketsRoute
  '/nova-ocorrencia': typeof AppNovaOcorrenciaRoute
  '/tickets-internos': typeof AppTicketsInternosRoute
  '/gestor/kpis': typeof AppGestorKpisRoute
  '/nps/respostas': typeof AppNpsRespostasRoute
  '/ticket/$int': typeof AppTicketIntRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/meus-tickets': typeof AppMeusTicketsRoute
  '/nova-ocorrencia': typeof AppNovaOcorrenciaRoute
  '/tickets-internos': typeof AppTicketsInternosRoute
  '/gestor/kpis': typeof AppGestorKpisRoute
  '/nps/respostas': typeof AppNpsRespostasRoute
  '/ticket/$int': typeof AppTicketIntRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/meus-tickets': typeof AppMeusTicketsRoute
  '/_app/nova-ocorrencia': typeof AppNovaOcorrenciaRoute
  '/_app/tickets-internos': typeof AppTicketsInternosRoute
  '/_app/gestor/kpis': typeof AppGestorKpisRoute
  '/_app/nps/respostas': typeof AppNpsRespostasRoute
  '/_app/ticket/$int': typeof AppTicketIntRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/meus-tickets'
    | '/nova-ocorrencia'
    | '/tickets-internos'
    | '/gestor/kpis'
    | '/nps/respostas'
    | '/ticket/$int'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/meus-tickets'
    | '/nova-ocorrencia'
    | '/tickets-internos'
    | '/gestor/kpis'
    | '/nps/respostas'
    | '/ticket/$int'
  id:
    | '__root__'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/meus-tickets'
    | '/_app/nova-ocorrencia'
    | '/_app/tickets-internos'
    | '/_app/gestor/kpis'
    | '/_app/nps/respostas'
    | '/_app/ticket/$int'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tickets-internos': {
      id: '/_app/tickets-internos'
      path: '/tickets-internos'
      fullPath: '/tickets-internos'
      preLoaderRoute: typeof AppTicketsInternosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nova-ocorrencia': {
      id: '/_app/nova-ocorrencia'
      path: '/nova-ocorrencia'
      fullPath: '/nova-ocorrencia'
      preLoaderRoute: typeof AppNovaOcorrenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meus-tickets': {
      id: '/_app/meus-tickets'
      path: '/meus-tickets'
      fullPath: '/meus-tickets'
      preLoaderRoute: typeof AppMeusTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ticket/$int': {
      id: '/_app/ticket/$int'
      path: '/ticket/$int'
      fullPath: '/ticket/$int'
      preLoaderRoute: typeof AppTicketIntRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nps/respostas': {
      id: '/_app/nps/respostas'
      path: '/nps/respostas'
      fullPath: '/nps/respostas'
      preLoaderRoute: typeof AppNpsRespostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestor/kpis': {
      id: '/_app/gestor/kpis'
      path: '/gestor/kpis'
      fullPath: '/gestor/kpis'
      preLoaderRoute: typeof AppGestorKpisRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppMeusTicketsRoute: typeof AppMeusTicketsRoute
  AppNovaOcorrenciaRoute: typeof AppNovaOcorrenciaRoute
  AppTicketsInternosRoute: typeof AppTicketsInternosRoute
  AppGestorKpisRoute: typeof AppGestorKpisRoute
  AppNpsRespostasRoute: typeof AppNpsRespostasRoute
  AppTicketIntRoute: typeof AppTicketIntRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppMeusTicketsRoute: AppMeusTicketsRoute,
  AppNovaOcorrenciaRoute: AppNovaOcorrenciaRoute,
  AppTicketsInternosRoute: AppTicketsInternosRoute,
  AppGestorKpisRoute: AppGestorKpisRoute,
  AppNpsRespostasRoute: AppNpsRespostasRoute,
  AppTicketIntRoute: AppTicketIntRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
